word_list = {
    "bollywood movies": [
        "2 States",
        "3 Idiots",
        "7 Khoon maaf",
        "99",
        "Aa dekhen zaraa",
        "Aaja Nach Le",
        "Aap ki khatir",
        "Aashiqui 2",
        "Agent Vinod",
        "Agneepath",
        "Ahista Ahista",
        "Aisha",
        "Aiyya",
        "Ajab prem ki ghazab kahani",
        "Amu",
        "Ankhon Dekhi",
        "Antardwand",
        "Anthony kaun hai ?",
        "Apharan",
        "Apna sapna money money",
        "Atithi tum kab jaoge ?",
        "Aurangzeb",
        "Baabarr",
        "Babul",
        "Baby",
        "Bachna ae haseeno",
        "Banaras",
        "Band Baaja Baaraat",
        "Barfi",
        "Bas ek pal",
        "Being Cyrus",
        "Bengali Night",
        "Besharam",
        "Bewafaa",
        "Bewakoofiyan",
        "Bhagam bhag",
        "Bhaag Milkha Bhaag",
        "Bheja Fry",
        "Bhool bhulaiya",
        "Black",
        "Blue Umbrella, The",
        "Bluffmaster",
        "Bombay Talkies",
        "Break ke baad",
        "Bride and prejudice",
        "Bullett Raja",
        "Bunty aur Babli",
        "Chak de India",
        "Chalo Dilli",
        "Chance pe dance",
        "Chasm-e-buddoor",
        "Cheeni Kum",
        "Chennai Express",
        "Chintuji",
        "Chocolate",
        "Chup chup ke",
        "Cooking With Stella",
        "Corporate",
        "Dabangg",
        "Dabangg 2",
        "Daawat-e-Ishq",
        "D-Day",
        "Dedh Ishqiya",
        "Deewane huye paagal",
        "Delhi 6",
        "Delhi Belly",
        "Dev. D",
        "Dhan Dhana Dhan Goal",
        "Dhobi Ghat",
        "Dhoom 2",
        "Dhoom 3",
        "Dil bole hadippa",
        "Dil chahta hai",
        "Dil kabaddi",
        "Dil pe mat le yaar",
        "Dil to bachcha hai ji",
        "The Dirty Picture",
        "Do Dooni Char",
        "Dolly ki Doli",
        "Don",
        "Don 2",
        "Dor",
        "Dostana",
        "Drona",
        "Dum Maaro Dum",
        "Dus",
        "Dus Kahaniyan",
        "Ek Ajnabee",
        "Ek Chalis ki last local",
        "Eklavya",
        "Ek Main aur Ek Tu",
        "Ek This Daayan",
        "English Vinglish",
        "Everybody says I'm fine",
        "Fanaa",
        "Fashion",
        "Finding Fanny",
        "Fukrey",
        "Gandhi my father",
        "Gangs of Wasseypur 1",
        "Gangs of Wasseypur 2",
        "Gangster",
        "Ghajini",
        "Ghanchakkar",
        "Go Goa Gone",
        "Golmaal",
        "Gori Tere Pyaar Mein",
        "Gulaal",
        "Gulaab Gang",
        "Gunday",
        "Guru",
        "Haasil",
        "Haider",
        "Halla bol",
        "Happy Ending",
        "Hari-bhari",
        "Harishchandrachi Factory",
        "Hasee Toh Phasee",
        "Hazaar chaurasi ki maa",
        "Hazaron khwaishen aisi",
        "Hello",
        "Heyy babyy",
        "Home Delivery",
        "Honeymoon Travels Pvt. Ltd.",
        "Hulla",
        "Hum-tum",
        "I am Kalam",
        "I hate Luv Storys",
        "I see you",
        "Ishqiya",
        "Iqbal",
        "Jaane bhi do yaaro",
        "Jaane tu ya jaane na",
        "James",
        "Jaan-e-man",
        "Jab we met",
        "Jhoom Barabar Jhoom",
        "Jhootha hi sahi",
        "Jo bole so nihaal",
        "Jodhaa Akbar",
        "Johnny Gaddar",
        "Jolly LLB",
        "Jurm",
        "Just Married",
        "Kaal",
        "Kabhi alvida na kehna",
        "Kabhi khushi kabhi gam",
        "Kahaani",
        "Kai Po Che",
        "Kaminey",
        "Karam",
        "Karthik calling Karthik",
        "Kaun",
        "Khamosh Pani",
        "Khoobsurat",
        "Khosla ka ghosla",
        "Khoya khoya chand",
        "Kill/Dil",
        "Kites",
        "Krrish",
        "Krrish 3",
        "Kuch meetha ho jaaye",
        "Kurbaan",
        "Kya kool hai hum",
        "Laaga chunari mein daag",
        "Lakshya",
        "Lage raho Munna bhai",
        "Life in a metro",
        "Listen Amaya",
        "Loins of Punjab",
        "Lootera",
        "Love Aaj Kal",
        "Love Sex aur Dhokha",
        "Luck",
        "Luck by chance",
        "Lucky",
        "The Lunchbox",
        "Luv Shuv Tey Chicken Khurana",
        "Maalamaal Weekly",
        "Madras Cafe",
        "Main meri patni aur woh",
        "Main zinda hoon",
        "Maine Gandhi ko nahin maara",
        "Maine pyar kyun kiya",
        "Mangal Pandey",
        "Manorama six feet under",
        "Mardaani",
        "Mary Kom",
        "Mast",
        "Matru ki Bijlee ka Mandola",
        "Maqbool",
        "Mausam",
        "Mera pehla pehla pyar",
        "Mere Brother ki Dulhan",
        "Mistress of Spices",
        "Mithya",
        "Morning raga",
        "Mujhse Fraandship Karoge",
        "My brother Nikhil",
        "My father's daughter",
        "My name is Anthony Gonsalves",
        "My name is Khan",
        "My wife's murder",
        "Namastey London",
        "Namesake, The",
        "Nautanki Sala",
        "New York",
        "No One Killed Jessica",
        "OMG: Oh My God",
        "Omkara",
        "Om Shanti Om",
        "Once upon a time in Mumbai",
        "Other end of the line, The",
        "Oye lucky lucky oye",
        "Paan Singh Tomar",
        "Page 3",
        "Paheli",
        "Parineeta",
        "Partner",
        "Patiala House",
        "Peepli Live",
        "Phir hera pheri",
        "P.K.",
        "Prem Rog",
        "Pyar ka Punchnama",
        "Pyar ke side effects",
        "Queen",
        "Raanjhanaa",
        "Raavan",
        "Rab ne bana di jodi",
        "Race",
        "Raincoat",
        "Rajneeti",
        "Ramchand Pakistani",
        "Ram Leela",
        "Rang de basanti",
        "Ra One",
        "Revolver Rani",
        "Risk",
        "Road, Movie",
        "Rock On",
        "Rocket Singh : Salesman of the year",
        "Rock Star",
        "Rules",
        "Saathiya",
        "Saheb, Biwi aur Gangster",
        "Salaam-e-ishq",
        "Salaam Namaste",
        "Sandcastle",
        "Sankat City",
        "Sarkar",
        "Sehar",
        "Shaadi Ke side Effects",
        "Shahid",
        "Shaitan",
        "Shakti",
        "Shanghai",
        "Shikhar",
        "Shool",
        "Shor in the City",
        "Shuddh Desi Romance",
        "Sikandar",
        "Singham",
        "Singh is king",
        "Slumdog Millionaire",
        "Socha na tha",
        "Sorry bhai",
        "Special Chabbis Special 26",
        "Supermen of Malegaon",
        "Super star",
        "Swades",
        "Swami",
        "Taal",
        "Taare zameen par",
        "Table No.",
        "Talaash",
        "Tango Charlie",
        "Tanu weds Manu",
        "Ta ra rum pum",
        "Tashan",
        "Taxi No. 9211",
        "Teen Deewarein",
        "Tera mera saath rahe",
        "Tevar",
        "That Girl in Yellow Boots",
        "The film",
        "Traffic Signal",
        "Udaan",
        "Ugly aur pagli",
        "Veedu mini review",
        "Veer-zaara",
        "Vicky Donor",
        "Viruddh",
        "Vivah",
        "Wake up Sid!",
        "Waqt",
        "Water",
        "A Wednesday",
        "Welcome",
        "Welcome to Sajjanpur",
        "Well Done Abba",
        "What's your rashee",
        "Woh Lamhe",
        "Yahaan",
        "Yakeen",
        "Yeh Jawaani Hai Deewani",
        "Yeh Saali Zindagi",
        "Yun hota to kya hota",
        "Yuva",
        "Zeher",
        "Zinda",
        "Zindagi na milegi dobara",
        "Zubeida",
        ""
    ],
    "pokemons": [
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Nidoran\u2640",
        "Nidorina",
        "Nidoqueen",
        "Nidoran\u2642",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetch'd",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew"
    ],
    "animals": [
        "albatross",
        "alligator",
        "aardwark",
        "ant",
        "bear",
        "bee",
        "bird",
        "camel",
        "cat",
        "cheetah",
        "chicken",
        "chimpanzee",
        "cow",
        "crocodile",
        "deer",
        "dog",
        "dolphin",
        "duck",
        "eagle",
        "elephant",
        "fish",
        "fly",
        "fox",
        "frog",
        "giraffe",
        "goat",
        "goldfish",
        "hamster",
        "hippopotamus",
        "hyena",
        "horse",
        "kangaroo",
        "kitten",
        "lion",
        "lobster",
        "monkey",
        "octopus",
        "owl",
        "panda",
        "pig",
        "puppy",
        "rabbit",
        "rat",
        "rhinosaurus",
        "scorpion",
        "seal",
        "shark",
        "sheep",
        "snail",
        "snake",
        "spider",
        "squirrel",
        "tiger",
        "turtle",
        "wolf",
        "zebra"
    ],
    "fruits": [
        "apple",
        "apricot",
        "avocado",
        "banana",
        "berry",
        "cantaloupe",
        "cherry",
        "citron",
        "citrus",
        "coconut",
        "date",
        "fig",
        "grape",
        "guava",
        "kiwi",
        "lemon",
        "lime",
        "mango",
        "melon",
        "mulberry",
        "nectarine",
        "orange",
        "papaya",
        "peach",
        "pear",
        "pineapple",
        "plum",
        "prune",
        "raisin",
        "raspberry",
        "tangerine"
    ],
    "countries": [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua & Deps",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Central African Rep",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo {Democratic Rep}",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "East Timor",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland {Republic}",
        "Israel",
        "Italy",
        "Ivory Coast",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea North",
        "Korea South",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar, {Burma}",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "St Kitts & Nevis",
        "St Lucia",
        "Saint Vincent & the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome & Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga",
        "Trinidad & Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ]
}
